#!/bin/bash
msg=""
skip=1
flag1=false
flag2=false
cat /dev/ttyACM0 | while read msg; do
  let "skip++"
  if [[ $skip -lt 3 ]] 
  then
    continue
  fi  
  echo "$msg"
  msg=${msg:1}
  NodeId=${msg:7:2}
  echo "$NodeId"
  update=""
  if [[ $NodeId == 45 ]] 
  then  
    apiKey="Y07QGUBLUWD22E7X"
    flag1=true
    msg="${msg/Temp=/field1=}"  
    msg="${msg/Lux=/field2=}"
    msg="${msg/Millivolts=/field3=}"
  fi  
  if [[ $NodeId == 71 ]] 
  then  
    apiKey="64VU333KPHUIGPNP"
    flag2=true
    msg="${msg/Temp=/field1=}"  
    msg="${msg/Lux=/field2=}"
    msg="${msg/Millivolts=/field3=}"
    msg="${msg/Soil=/field4=}"
    msg="${msg/Temp2=/field5=}"
    msg="${msg/Humidity=/field6=}"
  fi    
  IFS='|' read -ra ADDR <<< "$msg"
  for i in "${ADDR[@]}"; do
    if [[ $i == field* ]]
    then  
      update="$update&$i"
    fi  
  done
  update=${update:1}
  echo "$update"
  curl --silent --request POST --header "X-THINGSPEAKAPIKEY: $apiKey" --data "$update" "http://api.thingspeak.com/update"

  if [ $skip == 7 ] || ([ $flag1 == true ] && [ $flag2 == true ]); then
    break
  fi  
done


