#!/bin/bash
apiKey="64VU333KPHUIGPNP"
msg=""
skip=1
flag=false
cat /dev/ttyUSB0 | while read msg; do
  let "skip++"
  if [[ $skip -lt 3 ]] 
  then
    continue
  fi  
  echo "$msg"
  msg=${msg:1}
  NodeId=${msg:7:2}
  echo "$NodeId"
  update=""
  if [[ $NodeId == 71 ]] 
  then  
    flag=true
    msg="${msg/Temp=/field1=}"  
    msg="${msg/Lux=/field2=}"
    msg="${msg/Millivolts=/field3=}"
    msg="${msg/Soil=/field4=}"
    msg="${msg/Temp2=/field5=}"
    msg="${msg/Humidity=/field6=}"
  fi  
  IFS='|' read -ra ADDR <<< "$msg"
  for i in "${ADDR[@]}"; do
    if [[ $i == field* ]]
    then  
      update="$update&$i"
    fi  
  done
  update=${update:1}
  echo "$update"
  if [[ $flag == true ]] 
  then
    curl --silent --request POST --header "X-THINGSPEAKAPIKEY: $apiKey" --data "$update" "https://api.thingspeak.com/update"
  fi
  if [ $skip == 50 ] || [ $flag == true ]; then
    break
  fi  
done


