#!/bin/bash
apiKey="TD5ODXR1W42SDF6F" # ThingSpeak channel write API key, put your own
msg=""
skip=0
cat /dev/ttyUSB0 | while read msg; do
  let "skip++"
  if [[ $skip -lt 3 ]] 
  then
    continue
  fi  
  echo "$msg"
  msg="${msg/ExtT=/field3=}"  
  msg="${msg/T=/field1=}"
  msg="${msg/IntLux=/field2=}"
  msg="${msg/ExtLux=/field4=}"
  update=""
  IFS='|' read -ra ADDR <<< "$msg"
  for i in "${ADDR[@]}"; do
    if [[ $i == field* ]]
    then  
      update="$update&$i"
    fi  
  done
  update=${update:1}
  echo "$update"
  curl --silent --request POST --header "X-THINGSPEAKAPIKEY: $apiKey" --data "$update" "http://api.thingspeak.com/update"
  if [[ $skip == 3 ]] 
  then
    break
  fi  
done


