#!/bin/bash
msg=""
skip=1
flag1=false
flag2=false
updated1=false
updated2=false
cat /dev/ttyUSB0 | while read msg; do
  let "skip++"
  if [[ $skip -lt 3 ]] 
  then
    continue
  fi  
  echo "$msg"
  msg=${msg:1}
  NodeId=${msg:7:2}
  echo "$NodeId"
  update=""
  if [[ $NodeId == 45 ]] 
  then  
    flag1=true
    msg="${msg/Temp=/field1=}"  
    msg="${msg/Lux=/field2=}"
    msg="${msg/Millivolts=/field3=}"
  fi  
  if [[ $NodeId == 71 ]] 
  then  
    flag2=true
    msg="${msg/Temp=/field1=}"  
    msg="${msg/Lux=/field2=}"
    msg="${msg/Millivolts=/field3=}"
    msg="${msg/Soil=/field4=}"
    msg="${msg/Temp2=/field5=}"
    msg="${msg/Humidity=/field6=}"
  fi    
  IFS='|' read -ra ADDR <<< "$msg"
  for i in "${ADDR[@]}"; do
    if [[ $i == field* ]]
    then  
      update="$update&$i"
    fi  
  done
  update=${update:1}
  echo "$update"
  if [ $flag1 == true ] && [$updated1==false]; then
    apiKey="Y07QGUBLUWD22E7X"
    curl --silent --request POST --header "X-THINGSPEAKAPIKEY: $apiKey" --data "$update" "https://api.thingspeak.com/update"
    updated1=true
  fi
  if [ $flag2 == true ] && [$updated2==false]; then
    apiKey="64VU333KPHUIGPNP"
    curl --silent --request POST --header "X-THINGSPEAKAPIKEY: $apiKey" --data "$update" "https://api.thingspeak.com/update"
    updated2=true
  fi
  if [ $skip == 10 ] || ([ $flag1 == true ] && [ $flag2 == true ]); then
    break
  fi  
done


